#include "dados.h"

const char *const cidades[] = {
    "Ceilândia",
    "Samambaia",
    "Taguatinga",
    "Plano Piloto",
    "Planaltina",
    "Águas Claras",
    "Recanto das Emas",
    "Gama",
    "Guará",
    "Santa Maria",
    "Sobradinho II",
    "São Sebastião",
    "Vicente Pires",
    "Itapoã",
    "Sobradinho",
    "Sudoeste",
    "Brazlândia",
    "Riacho Fundo II",
    "Paranoá",
    "Riacho Fundo",
    "Estrutural",
    "Lago Norte",
    "Cruzeiro",
    "Lago Sul",
    "Jardim Botânico",
    "Núcleo Bandeirante",
    "Park Way",
    "Candangolândia",
    "Varjão",
    "Fercal",
    "SIA"
};

const char *const nomes[] = {
    "Laura",
    "Beatriz",
    "Maria",
    "Ana",
    "Júlia",
    "Alice",
    "Mariana",
    "Larissa",
    "Maria Eduarda",
    "Sofia",
    "Isabela",
    "Camila",
    "Helena",
    "Lara",
    "Valentina",
    "Letícia",
    "Luana",
    "Amanda",
    "Yasmin",
    "Sophia",
    "Rebeca",
    "Juliana",
    "Bruna",
    "Fernanda",
    "Cecília",
    "Isadora",
    "Lorena",
    "Lívia",
    "Manuela",
    "Vitória",
    "Miguel",
    "Lucas",
    "Guilherme",
    "Gabriel",
    "Arthur",
    "Enzo",
    "Rafael",
    "João",
    "Gustavo",
    "Pedro",
    "Bernardo",
    "Matheus",
    "Davi",
    "Heitor",
    "Henrique",
    "Bruno",
    "Samuel",
    "Felipe",
    "Lorenzo",
    "Benjamim",
    "Vinícius",
    "Rodrigo",
    "Eduardo",
    "Diego",
    "Antônio",
    "Leonardo",
    "Nicolas",
    "Noah",
    "Daniel",
    "Thiago"
};

const char *const sobrenomes[] = {
    "Agostinho",
    "Aguiar",
    "Alegria",
    "Alencastro",
    "Alvim",
    "Amorim",
    "Apolinário",
    "Araújo",
    "Arruda",
    "Assis",
    "Ávila",
    "Azambuja",
    "Baptista",
    "Barros",
    "Beira-Mar",
    "Belchior",
    "Belém",
    "Botelho",
    "Brito",
    "Caetano",
    "Calixto",
    "Camilo",
    "Capelo",
    "Castro",
    "Cavalcante",
    "Conceição",
    "Corte Real",
    "Cortês",
    "Cunha",
    "Curado",
    "Custódio",
    "Córdoba",
    "Damásio",
    "Dinís",
    "Drumond",
    "Escobar",
    "Espinosa",
    "Evangelista",
    "Farias",
    "Figueiredo",
    "Figueiroa",
    "Flores",
    "Freitas",
    "Frutuoso",
    "Furtado",
    "Félix",
    "Garcia",
    "Gaspar",
    "Gil",
    "Gonzaga",
    "Gouveia",
    "Guimarães",
    "Góis",
    "Hilário",
    "Hipólito",
    "Ibrahim",
    "Ilha",
    "Infante",
    "Jesus",
    "Jordão",
    "Lacerda",
    "Lancastre",
    "Machado",
    "Maciel",
    "Magalhães",
    "Maia",
    "Mello",
    "Menezes",
    "Mesquita",
    "Morgado",
    "Moura",
    "Neves",
    "Novais",
    "Nóbrega",
    "Ornélas",
    "Oliveira",
    "Ourique",
    "Pacheco",
    "Padilha",
    "Paiva",
    "Paraíso",
    "Paris",
    "Peralta",
    "Pilar",
    "Pinheiro",
    "Portela",
    "Queiroz",
    "Rebelo",
    "Salazar",
    "Salgado",
    "Salgueiro",
    "Subtil",
    "Varela",
    "Veiga",
    "Veloso",
    "Xavier",
    "Xisco",
    "Zagalo",
    "Zanette",
    "Zaganelli",
    "Abravanel",
    "Albuquerque",
    "Alencar",
    "Almada",
    "Álvares",
    "Alves",
    "Amoreira",
    "Andrade",
    "Annenberg",
    "Antena",
    "Antunes",
    "Aparício",
    "Arantes",
    "Aroeira",
    "Arriaga",
    "Assumpção",
    "Assunção",
    "Banheira",
    "Barata",
    "Barcellos",
    "Barcelos",
    "Barreira",
    "Barreto",
    "Barroso",
    "Bastos",
    "Beltrão",
    "Bentes",
    "Bernardes",
    "Bernardi",
    "Bial",
    "Bittencourt",
    "Boaventura",
    "Bonfim",
    "Bongiovanni",
    "Bonner",
    "Bouças",
    "Brites",
    "Brum",
    "Bulhões",
    "Cabreira",
    "Cachoeira",
    "Caldas",
    "Caldeira",
    "Camacho",
    "Campos",
    "Carneiro",
    "Carreira",
    "Carvalheira",
    "Carvalho",
    "Caseira",
    "Casqueira",
    "Castanheira",
    "Castanho",
    "Castelo",
    "Castiel",
    "Cerqueira",
    "Chapelin",
    "Chaves",
    "Close",
    "Coqueiro",
    "Corte",
    "Coutinho",
    "Crespo",
    "D’Ávila",
    "da Aldeia",
    "da Bandeira",
    "da Barra",
    "da Barranca",
    "da Conceição",
    "da Costa",
    "da Cruz",
    "da Cunha",
    "da Fonseca",
    "da Fontoura",
    "da Fronteira",
    "da Gama",
    "da Luz",
    "da Madureira",
    "da Maia",
    "da Mata",
    "da Mota",
    "da Nóbrega",
    "da Paz",
    "da Penha",
    "da Rocha",
    "da Rosa",
    "da Silva",
    "da Silveira",
    "da Terra",
    "da Veiga",
    "Dantas",
    "das Neves",
    "Datena",
    "de Assunção",
    "de Borba",
    "de Lara",
    "de Lins",
    "de Oliveira",
    "de Quadros",
    "de Sá",
    "Dias",
    "Dieckmann",
    "Diegues",
    "do Prado",
    "Dolabella",
    "Domingues",
    "Dorneles",
    "dos Reis",
    "Drummond",
    "Duarte",
    "Espinheira",
    "Espinhosa",
    "Esteves",
    "Evelyn",
    "Fagundes",
    "Falabella",
    "Fernandes",
    "Ferraço",
    "Ferrari",
    "Ferraz",
    "Ferreira",
    "Figueira",
    "Filgueira",
    "Fischer",
    "Fogaça",
    "Fontenelle",
    "Fontes",
    "Fontinhas",
    "Gabeira",
    "Galego",
    "Galvão",
    "Ganzarolli",
    "Garcês",
    "Garcez",
    "Gentil",
    "Geraldes",
    "Giácomo",
    "Gimenez",
    "Godinho",
    "Godins",
    "Gomes",
    "Gomide",
    "Gonçalves",
    "Goulart",
    "Grotas",
    "Guedes",
    "Guterres",
    "Henriques",
    "Hermingues",
    "Hernandes",
    "Hickmann",
    "Jaques",
    "Junqueira",
    "Kannenberg",
    "Lafaiete",
    "Lambertini",
    "Laranjeira",
    "Leiria",
    "Lessa",
    "Liberato",
    "Limeira",
    "Lins",
    "Lobos",
    "Lombardi",
    "Longuinho",
    "Lopes",
    "Louzada",
    "Macieira",
    "Madeira",
    "Maldonado",
    "Mangueira",
    "Marcondes",
    "Marinho",
    "Marins",
    "Marques",
    "Martim",
    "Martins",
    "Matoso",
    "Mazzaropi",
    "Medeiros",
    "Meira",
    "Meireles",
    "Mendanha",
    "Mendes",
    "Meneghel",
    "Menendes",
    "Modesto",
    "Moniz",
    "Monteira",
    "Monteiro",
    "Montenegro",
    "Moraes",
    "Morais",
    "Moreira",
    "Moreno",
    "Moscovis",
    "Müller",
    "Munhoz",
    "Muniz",
    "Negrão",
    "Nogueira",
    "Noronha",
    "Novaes",
    "Nunes",
    "Ordonhes",
    "Ornelas",
    "Ouriques",
    "Paes",
    "Palhares",
    "Palmeira",
    "Parreira",
    "Passarinho",
    "Pedroso",
    "Peixoto",
    "Pereira",
    "Peres",
    "Pimenta",
    "Pinheira",
    "Porteira",
    "Porto",
    "Quaresma",
    "Quarteira",
    "Raia-",
    "Ramalho",
    "Rameira",
    "Ramires",
    "Ramos",
    "Rebouças",
    "Rêgo",
    "Regueira",
    "Resende",
    "Reymond",
    "Rezende",
    "Ribas",
    "Ribeira",
    "Ribeiro",
    "Riche",
    "Rios",
    "Rodrigues",
    "Rolim",
    "Roriz",
    "Roseira",
    "Sais",
    "Sales",
    "Sampaio",
    "Sanches",
    "Santana",
    "Schmütz",
    "Schoemberger",
    "Schumacher",
    "Sheherazade",
    "Silveira",
    "Silverstone",
    "Simão",
    "Simões",
    "Siqueira",
    "Siqueiro",
    "Soares",
    "Soeira",
    "Solimões",
    "Steves",
    "Tavares",
    "Taveira",
    "Teixeira",
    "Teles",
    "Timberg",
    "Torres",
    "Trindade",
    "Vargas",
    "Vasconcelos",
    "Vasques",
    "Velasques",
    "Veles",
    "Vidal",
    "Videira",
    "Vieira",
    "Vilela",
    "Vimaranes",
    "Vitti",
    "Viveiros",
    "Werneck",
    "Ximenes",
};

const unsigned long N_CIDADES = sizeof(cidades)/sizeof(cidades[0]);
const unsigned long N_NOMES = sizeof(nomes)/sizeof(nomes[0]);
const unsigned long N_SOBRENOMES = sizeof(sobrenomes)/sizeof(sobrenomes[0]);
